www/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'plantas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'www.views.index', name='index'),
    url(r'^(?P<planta_id>\d+)/$', 'www.views.detail', name='detail'),
    url(r'^login/$', 'www.views.loginView', name='loginView'),
    url(r'^logout/$', 'www.views.logoutView', name='logoutView'),

)

www/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class TipoSuelo(models.Model):
	nombre = models.CharField(max_length=100)
	def __unicode__(self):
		return u"%s" % (self.nombre)

class Planta(models.Model):
	nombreCientifico = models.CharField(max_length=150)
	nombreComun = models.CharField(max_length=150)
	foto = models.ImageField(upload_to="gfa/", blank=True, null=True)
	detalleHoja = models.ImageField(upload_to="gfa/", blank=True, null=True)
	distribucion = models.CharField(max_length=100)
	longitud = models.CharField(max_length=50)
	tipoDeSuelo = models.ForeignKey(TipoSuelo)
	altitud = models.CharField(max_length=50)
	creador = models.ForeignKey(User)
	def __unicode__(self):
		return  u"%s (%s)" % (self.nombreCientifico, self.nombreComun)

www/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from www.models import Planta, TipoSuelo
from django.core.context_processors import csrf
from django import forms
from django.http import HttpResponseRedirect

# Create your views here.

class PlantaForm(forms.ModelForm):
    class Meta:
        model = Planta
        fields = ['nombreCientifico','altitud','nombreComun','foto','detalleHoja','distribucion','longitud']
        widgets = {
            'nombreCientifico': forms.TextInput(attrs={'class': 'form-control'}),
            'nombreComun': forms.TextInput(attrs={'class': 'form-control'}),
            'distribucion': forms.TextInput(attrs={'class': 'form-control'}),
            'longitud': forms.TextInput(attrs={'class': 'form-control'}),
            'altitud': forms.TextInput(attrs={'class': 'form-control'}),
        }


@login_required(login_url='/login/')
def index(request):
	if request.method == 'POST': # If the form has been submitted...
		form = PlantaForm(request.POST, request.FILES) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			obj = form.save(commit=False)
			obj.creador = request.user
			if request.POST['tipoDeSuelo'] == 'other':
				suelo = TipoSuelo(nombre=request.POST['sueloOther'])
				suelo.save()
			else:
				suelo = TipoSuelo.objects.get(nombre=request.POST['tipoDeSuelo'])
			obj.tipoDeSuelo = suelo
			obj.save()

	form = PlantaForm() # An unbound form
	tiposSuelo = TipoSuelo.objects.all()
	plantas = Planta.objects.all()
	context = {	'form':form,
				'plantas':plantas,
				'tiposSuelo': tiposSuelo};

	return render(request, 'index.htm', context)

def detail(request, planta_id):
	planta = get_object_or_404(Planta, pk=planta_id)
	context = {'planta': planta,}
	return render(request, 'planta.htm', context)

def loginView(request):
	if request.user.is_authenticated():
		return redirect('/')
	else:
		if request.method=='POST':
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					# Redirect to a success page.
					return redirect('/')
				else:
					# Return a 'disabled account' error message
					error = 'Su cuenta ha sido deshabilitada.'
					context = {'error': error}
					context.update(csrf(request))
					return render(request, 'login.htm', context)
			else:
				error = 'Su nombre de usuario o contraseña son incorrectos'
				context = {'error': error}
				context.update(csrf(request))
				return render(request, 'login.htm', context)
		else:
			context = {}
			context.update(csrf(request))
			return render(request, 'login.htm', context)

def logoutView(request):
	logout(request)
	return redirect('/login/')

www/templates/base.htm
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Guía Forestal de Andalucía{% block titulo %}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
    body {
  		padding-top: 50px;
	}
	@media(max-width: 768px){
		body{
			padding-top: 80px;
		}
	}
    </style>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<a href="/" class="navbar-brand">Guía Forestal de Andalucía</a>
	<ul class="nav navbar-nav">
	{% block botones %}{% endblock %}
  	</ul>
	<p class="navbar-text pull-right">Conectado como {{ user.get_full_name }} <a href="./logout/" class="navbar-link">(desconectar)</a></p>
</nav>
{% block content %}{% endblock %}
</body>
</html>

www/templates/index.htm
{% extends "base.htm" %}
{% block titulo %} - Índice{% endblock %}
{% block botones %}
<li><a href data-toggle="modal" data-target="#formularioPlanta">Añadir planta</a></li>
{% endblock %}
{% block content %}
<div class="container">
	<table class="table table-striped" style="margin-top:50px; text-align:center !important;">
	  <tr>
	  	<th style="text-align:center !important;">Nombre Científico</th>
	  	<th style="text-align:center !important;">Nombre Común</th>
	  	<th style="text-align:center !important;">Longitud</th>
	  	<th style="text-align:center !important;">Distribución</th>
	  	<th style="text-align:center !important;">Tipo de Suelo</th>
	  	<th style="text-align:center !important;">Altitud</th>
	  	<th style="text-align:center !important;">Añadido por</th>
	  </tr>
	  {% for planta in plantas %}
	  <tr>
	  	<td><a href="/{{ planta.id }}/">{{ planta.nombreCientifico }}</a></td>
	  	<td>{{ planta.nombreComun }}</td>
	  	<td>{{ planta.longitud }}</td>
	  	<td>{{ planta.distribucion }}</td>
	  	<td>{{ planta.tipoDeSuelo }}</td>
	  	<td>{{ planta.altitud }}</td>
	  	<td>{{ planta.creador }}</td>
	  </tr>
	  {% endfor %}
	</table>
</div>


<div class="modal fade" id="formularioPlanta" tabindex="-1" role="dialog" aria-labelledby="etiquetaForm" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Añadir planta</h4>
      </div>
      <div class="modal-body">

		<form action="/" method="POST" role="form" enctype="multipart/form-data" >
			{% csrf_token %}
		  <div class="form-group">
		    <label for="id_nombreCientifico">Nombre Científico</label>
		    {{ form.nombreCientifico }}
		  </div>
		  <div class="form-group">
		    <label for="id_nombreComun">Nombre Común</label>
		    {{ form.nombreComun }}
		  </div>
		  <div class="form-group">
		    <label for="id_foto">Foto</label>
		    {{ form.foto }}
		  </div>
		  <div class="form-group">
		    <label for="id_detalleHoja">Foto de la Hoja</label>
		    {{ form.detalleHoja }}
		  </div>
		  <div class="form-group">
		    <label for="id_distibucion">Distribución</label>
		    {{ form.distribucion }}
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Tipo de suelo</label>
		    <div class="row">
	 			<div class="col-xs-6">
					<select id="tipoDeSuelo" name="tipoDeSuelo" class="form-control">
						{% for tipo in tiposSuelo %}
						<option value="{{ tipo.nombre }}">{{ tipo.nombre }}</option>
						{% endfor %}
						<option value="other">Otro</option>
					</select>
				</div>
				<div class="col-xs-6">
			    	<input type="text" class="form-control" id="sueloOther" name="sueloOther" placeholder="Otro">
			    </div>
			</div>
		  </div>
		  <div class="form-group">
		    <label for="id_longitud">Longitud</label>
		    {{ form.longitud }}
		  </div>
		  <div class="form-group">
		    <label for="id_altitud">Altitud</label>

				{{ form.altitud }}		  
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </form>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript">
var $tiposSuelo = $('#tipoDeSuelo'), $otherInput = $('#sueloOther');
$tiposSuelo.change(function () {
    if ($tiposSuelo.val() == 'other') {
        $otherInput.removeAttr('disabled');
    } else {
        $otherInput.attr('disabled', 'disabled').val('');
    }
}).trigger('change'); // added trigger to calculate initial state
</script>
{% endblock %}

www/templates/login.htm
<!DOCTYPE html>
<html lang="es">
<head>
	<title>Guía Forestal de Andalucía - Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
    body {
  		padding-top: 50px;
	}
    </style>
</head>
<body>

<div class="jumbotron text-center" style="padding:30px 0px 30px 0px">
  <h2>Guía Forestal de Andalucía</h2>
  <form method="POST" action="/login/" role="form">
  	{% csrf_token %}
  	<div class="row" style="margin-top: 60px;">
  		<div class="col-md-4 col-md-offset-4">
  			 <p><input type="text" class="form-control" name="username" placeholder="Usuario" required></p>
  			 <p><input type="password" class="form-control" name="password" placeholder="Contraseña" required></p>
  		</div>
  	</div>
    {% if error %}
            <p><div class="alert alert-danger">
              {{ error }}
            </div></p>
    {% endif %}
    <p><button type="submit" class="btn btn-primary" role="button">Acceder</button></p>
  </form>
</div>


</body>
</html>

www/templates/planta.htm
{% extends "base.htm" %}
{% block titulo %} - {{ planta.nombreCientifico }}{% endblock %}
{% block botones %}
<li><a href data-toggle="modal" data-target="#editarPlanta">Editar planta</a></li>
{% endblock %}
{% block content %}
<div class="container" style="margin-top:40px">

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>{{ planta.nombreCientifico }}</strong> <em>({{ planta.nombreComun }})</em></h3>
  </div>
  <div class="panel-body">
    <dl class="dl-horizontal">
    	<dt>Fotos</dt>
    	<dd><img src="{{ MEDIA_URL }}{{ planta.foto }}" style="width:240px; margin-right:15px;"><img src="{{ MEDIA_URL }}{{ planta.detalleHoja }}" style="width:240px"></dd>
        <dt>Nombre Científico</dt>
        <dd>{{ planta.nombreCientifico }}</dd>
        <dt>Nombre Común</dt>
        <dd>{{ planta.nombreComun }}</dd>
        <dt>Distribucion</dt>
        <dd>{{ planta.distribucion }}</dd>
        <dt>Longitud</dt>
        <dd>{{ planta.longitud }}</dd>
        <dt>Altitud</dt>
        <dd>{{ planta.altitud }}</dd>
        <dt>Tipo de Suelo</dt>
        <dd>{{ planta.tipoDeSuelo }}</dd>
      </dl>
  </div>
</div>

</div>

<div class="modal fade" id="editarPlanta" tabindex="-1" role="dialog" aria-labelledby="etiquetaForm" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Editar planta</h4>
      </div>
      <div class="modal-body">

		<form action="/" method="POST" role="form" enctype="multipart/form-data" >
			{% csrf_token %}
		  <div class="form-group">
		    <label for="id_nombreCientifico">Nombre Científico</label>
		    {{ form.nombreCientifico }}
		  </div>
		  <div class="form-group">
		    <label for="id_nombreComun">Nombre Común</label>
		    {{ form.nombreComun }}
		  </div>
		  <div class="form-group">
		    <label for="id_foto">Foto</label>
		    {{ form.foto }}
		  </div>
		  <div class="form-group">
		    <label for="id_detalleHoja">Foto de la Hoja</label>
		    {{ form.detalleHoja }}
		  </div>
		  <div class="form-group">
		    <label for="id_distibucion">Distribución</label>
		    {{ form.distribucion }}
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Tipo de suelo</label>
		    <div class="row">
	 			<div class="col-xs-6">
					<select id="tipoDeSuelo" name="tipoDeSuelo" class="form-control">
						{% for tipo in tiposSuelo %}
						<option value="{{ tipo.nombre }}">{{ tipo.nombre }}</option>
						{% endfor %}
						<option value="other">Otro</option>
					</select>
				</div>
				<div class="col-xs-6">
			    	<input type="text" class="form-control" id="sueloOther" name="sueloOther" placeholder="Otro">
			    </div>
			</div>
		  </div>
		  <div class="form-group">
		    <label for="id_longitud">Longitud</label>
		    {{ form.longitud }}
		  </div>
		  <div class="form-group">
		    <label for="id_altitud">Altitud</label>

				{{ form.altitud }}		  
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="submit" class="btn btn-primary">Guardar cambios</button>
        </form>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript">
var $tiposSuelo = $('#tipoDeSuelo'), $otherInput = $('#sueloOther');
$tiposSuelo.change(function () {
    if ($tiposSuelo.val() == 'other') {
        $otherInput.removeAttr('disabled');
    } else {
        $otherInput.attr('disabled', 'disabled').val('');
    }
}).trigger('change'); // added trigger to calculate initial state
</script>
</div>
{% endblock %}